config/routes.rb
Rails.application.routes.draw do
  resources :bingo_games do
    member do
      post :draw_number
      get :reset_numbers
    end
  end
  resources :bingo_numbers
  resources :bingo_cards do
    collection do
      delete :destroy_all
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/bingo_card.rb
class BingoCard < ApplicationRecord
  has_and_belongs_to_many :bingo_numbers
  has_and_belongs_to_many :bingo_games

  def initialize(params = {})
    super()
    
    if params[:bingo_game_id]
      @bingo_game = BingoGame.find(params[:bingo_game_id])  
      bingo_games << @bingo_game
    end
  end

  def pick_numbers
    %w(b i n g o).each do |letter|
      BingoNumber.where(letter: letter).sample(5).sort_by(&:number).each do |number|
        number.bingo_cards << self
      end
    end
  end

  def board_array
    arr = [[], [], [], [], []]
    %w(b i n g o).each do |letter|
      index = 0
      bingo_numbers.where(letter: letter).each do |number|
        arr[index] << number
        index += 1
      end
    end
    arr
  end

  def board_array_json
    { "board": board_array }
  end
end

app/controllers/bingo_cards_controller.rb
class BingoCardsController < ApplicationController
  before_action :set_bingo_card, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token


  # GET /bingo_cards or /bingo_cards.json
  def index
    @bingo_cards = BingoCard.all
  end

  # GET /bingo_cards/1 or /bingo_cards/1.json
  def show
    @bingo_card = BingoCard.find(params[:id])
  end

  # GET /bingo_cards/new
  def new
    @bingo_card = BingoCard.new
    @bingo_card.pick_numbers
    respond_to do |format|
      format.html { render partial: 'bingo_cards/bingo_card', locals: { bingo_card: @bingo_card } }
      format.json { render json: @bingo_card }
    end
  end

  # GET /bingo_cards/1/edit
  def edit; end

  # POST /bingo_cards or /bingo_cards.json
  def create
    @bingo_card = BingoCard.new(bingo_card_params)
    @bingo_card.pick_numbers
    locals = { bingo_card: @bingo_card }

    # This is to make the "New Bingo Card" button attach to a game, if desired.
    # Probably a better way to do this.
    if params[:bingo_card][:bingo_game_id]
      @bingo_game = BingoGame.find(params[:bingo_card][:bingo_game_id]) 
      locals[:bingo_game] = @bingo_game
    end

    respond_to do |format|
      if @bingo_card.save
        format.html { render partial: 'bingo_cards/bingo_card', locals: locals }
        format.json { render json: @bingo_card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bingo_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bingo_cards/1 or /bingo_cards/1.json
  def update
    respond_to do |format|
      if @bingo_card.update(bingo_card_params)
        format.html { redirect_to bingo_card_url(@bingo_card), notice: "Bingo card was successfully updated." }
        format.json { render :show, status: :ok, location: @bingo_card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bingo_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bingo_cards/1 or /bingo_cards/1.json
  def destroy
    @bingo_card.destroy

    respond_to do |format|
      format.html { redirect_to bingo_cards_url, notice: "Bingo card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def destroy_all
    BingoCard.destroy_all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bingo_card
      @bingo_card = BingoCard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bingo_card_params
      params.require(:bingo_card).permit(:winner, :bingo_game_id)
    end
end

app/helpers/bingo_cards_helper.rb
module BingoCardsHelper
end

app/views/bingo_cards/_bingo_card.html.erb
<div id="<%= dom_id bingo_card %>" class="col-sm-4">
  <table class="table table-bordered">
    <thead class="table-dark">
      <tr>
        <th class="text-center">B</th>
        <th class="text-center">I</th>
        <th class="text-center">N</th>
        <th class="text-center">G</th>
        <th class="text-center">O</th>
      </tr>
    </thead>
    <tbody>
      <% bingo_card.board_array.each do |row| %>
        <tr>
          <% row.each do |number| %>
            <%# Stimulus data attributes should replace this ERB logic %>
            <td class="text-center <%= "bg-success" if @bingo_game.bingo_numbers.include?(number) %>">
              <%= number.number %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bingo_cards/_bingo_cards.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bingo cards</h1>

<div data-controller="bingo-card" id="bingo_cards">
  <div data-bingo-card-target="appendBingoCard removeAllBingoCards" class="row">
  <% @bingo_cards.each do |bingo_card| %>
    <%= render bingo_card %>
  <% end %>
  </div>
  <%= button_tag 'New Bingo Card', data: {"game-id": @bingo_game.id, "action": "bingo-card#newCard"}, class: "btn btn-success" %>
  <%= button_tag 'Remove All Cards', data: {"game-id": @bingo_game.id, "action": "bingo-card#removeAllCards"}, class: "btn btn-danger" %>
</div>

app/views/bingo_cards/_form.html.erb
<%= form_with(model: bingo_card) do |form| %>
  <% if bingo_card.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bingo_card.errors.count, "error") %> prohibited this bingo_card from being saved:</h2>

      <ul>
        <% bingo_card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bingo_cards/edit.html.erb
<h1>Editing bingo card</h1>

<%= render "form", bingo_card: @bingo_card %>

<br>

<div>
  <%= link_to "Show this bingo card", @bingo_card %> |
  <%= link_to "Back to bingo cards", bingo_cards_path %>
</div>

app/views/bingo_cards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bingo cards</h1>

<div id="bingo_cards">
  <div class="row">
  <% @bingo_cards.each do |bingo_card| %>
    <%= render bingo_card %>
  <% end %>
</div>

<%= link_to "New bingo card", new_bingo_card_path %>

app/views/bingo_cards/new.html.erb
<h1>New bingo card</h1>

<%= render "form", bingo_card: @bingo_card %>

<br>

<div>
  <%= link_to "Back to bingo cards", bingo_cards_path %>
</div>

app/views/bingo_cards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bingo_card %>

<div>
  <%= link_to "Edit this bingo card", edit_bingo_card_path(@bingo_card) %> |
  <%= link_to "Back to bingo cards", bingo_cards_path %>
  <%= button_to "Destroy this bingo card", @bingo_card, method: :delete %>
</div>