config/routes.rb
Rails.application.routes.draw do
  resources :bingo_games do
    member do
      post :draw_number
      get :reset_numbers
    end
  end
  resources :bingo_numbers
  resources :bingo_cards do
    collection do
      delete :destroy_all
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/bingo_game.rb
class BingoGame < ApplicationRecord
  has_and_belongs_to_many :bingo_cards
  has_and_belongs_to_many :bingo_numbers

  def draw_number
    return nil unless possible_numbers.any?

    bingo_number = possible_numbers.sample
    bingo_numbers << bingo_number
    save!
    bingo_number
  end

  def possible_numbers
    @possible_numbers ||= BingoNumber.all - bingo_numbers
  end

  def reset_numbers
    bingo_numbers.destroy_all
  end

end

app/controllers/bingo_games_controller.rb
class BingoGamesController < ApplicationController
  before_action :set_bingo_game, only: %i[ show edit update destroy draw_number reset_numbers ]
  skip_before_action :verify_authenticity_token


  # GET /bingo_games or /bingo_games.json
  def index
    @bingo_games = BingoGame.all
  end

  # GET /bingo_games/1 or /bingo_games/1.json
  def show
    @bingo_cards = @bingo_game.bingo_cards
    @bingo_numbers = @bingo_game.bingo_numbers
    @possible_numbers = @bingo_game.possible_numbers
  end

  # GET /bingo_games/new
  def new
    @bingo_game = BingoGame.new
  end

  # GET /bingo_games/1/edit
  def edit
  end

  # POST /bingo_games or /bingo_games.json
  def create
    @bingo_game = BingoGame.new(bingo_game_params)

    respond_to do |format|
      if @bingo_game.save
        format.html { redirect_to bingo_game_url(@bingo_game), notice: "Bingo game was successfully created." }
        format.json { render :show, status: :created, location: @bingo_game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bingo_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bingo_games/1 or /bingo_games/1.json
  def update
    respond_to do |format|
      if @bingo_game.update(bingo_game_params)
        format.html { redirect_to bingo_game_url(@bingo_game), notice: "Bingo game was successfully updated." }
        format.json { render :show, status: :ok, location: @bingo_game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bingo_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bingo_games/1 or /bingo_games/1.json
  def destroy
    @bingo_game.destroy

    respond_to do |format|
      format.html { redirect_to bingo_games_url, notice: 'Bingo game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /bingo_games/1/draw_number
  def draw_number
    # draw_number returns a BingoNumber object or nil, if there are no more possible numbers
    number = @bingo_game.draw_number
    render plain: (number ? number.display : 'No more numbers available')
  end

  def reset_numbers
    @bingo_game.reset_numbers
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bingo_game
      @bingo_game = BingoGame.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bingo_game_params
      params.require(:bingo_game).permit(:name)
    end
end

app/helpers/bingo_games_helper.rb
module BingoGamesHelper
end

app/views/bingo_games/_bingo_game.html.erb
<div id="<%= dom_id bingo_game %>">
  <p>
    <strong>Name:</strong>
    <%= bingo_game.name %>
  </p>
  <p>
    <strong>Cards:</strong>
    <%= bingo_game.bingo_cards.size %>
  </p>
  <p>
    <strong>Called Numbers:</strong>
    <%= bingo_game.bingo_numbers.map { |n| n.display } %>
  </p>
  <p>
    <strong>Possible numbers:</strong>
    <%= bingo_game.possible_numbers.map { |n| n.display } %>
  </p>


</div>

app/views/bingo_games/_bingo_games.erb
<p style="color: green"><%= notice %></p>

<div id="bingo_games">
  <% @bingo_games.each do |bingo_game| %>
    <%= render bingo_game %>
    <p>
      <%= link_to "Show this bingo game", bingo_game %>
    </p>
  <% end %>
</div>

<%= link_to "New bingo game", new_bingo_game_path %>

app/views/bingo_games/_form.html.erb
<%= form_with(model: bingo_game) do |form| %>
  <% if bingo_game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bingo_game.errors.count, "error") %> prohibited this bingo_game from being saved:</h2>

      <ul>
        <% bingo_game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bingo_games/_number_picker.html.erb
<div data-controller="bingo-number">
  <h3 class="text-dark text-center bg-warning"  data-bingo-number-target="bingoNumber"></h3>

  <button data-action="bingo-number#newNumber" 
          data-game-id="<%= @bingo_game.id %>">
    Pick Number
  </button>
  <button data-action="bingo-number#resetNumbers" 
          data-game-id="<%= @bingo_game.id %>">
    Reset Numbers
  </button>
</div>

app/views/bingo_games/edit.html.erb
<h1>Editing bingo game</h1>

<%= render "form", bingo_game: @bingo_game %>

<br>

<div>
  <%= link_to "Show this bingo game", @bingo_game %> |
  <%= link_to "Back to bingo games", bingo_games_path %>
</div>

app/views/bingo_games/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bingo games</h1>

<div id="bingo_games">
  <% @bingo_games.each do |bingo_game| %>
    <%= render bingo_game %>
    <p>
      <%= link_to "Show this bingo game", bingo_game %>
    </p>
  <% end %>
</div>

<%= link_to "New bingo game", new_bingo_game_path %>

app/views/bingo_games/new.html.erb
<h1>New bingo game</h1>

<%= render "form", bingo_game: @bingo_game %>

<br>

<div>
  <%= link_to "Back to bingo games", bingo_games_path %>
</div>

app/views/bingo_games/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bingo_game %>
<%= render "number_picker" %>
<%= render "bingo_cards/bingo_cards", locals: {bingo_numbers: @bingo_game.bingo_numbers} %>

<div>
  <%= link_to "Edit this bingo game", edit_bingo_game_path(@bingo_game) %> |
  <%= link_to "Back to bingo games", bingo_games_path %>

  <%= button_to "Destroy this bingo game", @bingo_game, method: :delete %>
</div>