config/routes.rb
Rails.application.routes.draw do
  resources :bingo_games do
    member do
      post :draw_number
      get :reset_numbers
    end
  end
  resources :bingo_numbers
  resources :bingo_cards do
    collection do
      delete :destroy_all
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/bingo_number.rb
class BingoNumber < ApplicationRecord
  has_and_belongs_to_many :bingo_cards
  has_and_belongs_to_many :bingo_games

  def display
    "#{self.letter.upcase}#{self.number}"
  end
end

app/controllers/bingo_numbers_controller.rb
class BingoNumbersController < ApplicationController
  before_action :set_bingo_number, only: %i[ show edit update destroy ]

  # GET /bingo_numbers or /bingo_numbers.json
  def index
    @bingo_numbers = BingoNumber.all
  end

  # GET /bingo_numbers/1 or /bingo_numbers/1.json
  def show
  end

  # GET /bingo_numbers/new
  def new
    @bingo_number = BingoNumber.new
  end

  # GET /bingo_numbers/1/edit
  def edit
  end

  # POST /bingo_numbers or /bingo_numbers.json
  def create
    @bingo_number = BingoNumber.new(bingo_number_params)

    respond_to do |format|
      if @bingo_number.save
        format.html { redirect_to bingo_number_url(@bingo_number), notice: "Bingo number was successfully created." }
        format.json { render :show, status: :created, location: @bingo_number }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bingo_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bingo_numbers/1 or /bingo_numbers/1.json
  def update
    respond_to do |format|
      if @bingo_number.update(bingo_number_params)
        format.html { redirect_to bingo_number_url(@bingo_number), notice: "Bingo number was successfully updated." }
        format.json { render :show, status: :ok, location: @bingo_number }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bingo_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bingo_numbers/1 or /bingo_numbers/1.json
  def destroy
    @bingo_number.destroy

    respond_to do |format|
      format.html { redirect_to bingo_numbers_url, notice: "Bingo number was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bingo_number
      @bingo_number = BingoNumber.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bingo_number_params
      params.require(:bingo_number).permit(:bingo_card_id, :letter, :number)
    end
end

app/helpers/bingo_numbers_helper.rb
module BingoNumbersHelper
end

app/views/bingo_numbers/_bingo_number.html.erb
<div id="<%= dom_id bingo_number %>">
 <p>
    <strong>Bingo card:</strong>
    <%= bingo_number.bingo_card_ids %>
  </p>

  <p>
    <strong>Letter:</strong>
    <%= bingo_number.letter %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= bingo_number.number %>
  </p>

</div>

app/views/bingo_numbers/_form.html.erb
<%= form_with(model: bingo_number) do |form| %>
  <% if bingo_number.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bingo_number.errors.count, "error") %> prohibited this bingo_number from being saved:</h2>

      <ul>
        <% bingo_number.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :bingo_card_id, style: "display: block" %>
    <%= form.text_field :bingo_card_id %>
  </div>

  <div>
    <%= form.label :letter, style: "display: block" %>
    <%= form.text_field :letter %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bingo_numbers/edit.html.erb
<h1>Editing bingo number</h1>

<%= render "form", bingo_number: @bingo_number %>

<br>

<div>
  <%= link_to "Show this bingo number", @bingo_number %> |
  <%= link_to "Back to bingo numbers", bingo_numbers_path %>
</div>

app/views/bingo_numbers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bingo numbers</h1>

<div id="bingo_numbers">
  <% @bingo_numbers.each do |bingo_number| %>
    <%= render bingo_number %>
    <p>
      <%= link_to "Show this bingo number", bingo_number %>
    </p>
  <% end %>
</div>

app/views/bingo_numbers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bingo_number %>

<div>
  <%= link_to "Edit this bingo number", edit_bingo_number_path(@bingo_number) %> |
  <%= link_to "Back to bingo numbers", bingo_numbers_path %>

  <%= button_to "Destroy this bingo number", @bingo_number, method: :delete %>
</div>